name: cunit-tests
on: [push, pull_request]
jobs:
  run:
    name: CUnit tests
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: APT Update
      run: sudo apt-get update

    - name: Install CUnit
      run: sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev

    - name: Install SDL
      run: sudo apt-get install -y libsdl2-dev

    - name: CMake
      run: cmake .
    
    - name: Make
      run: make
    
    - name: Test
      run: ctest -V